package org.lwt.springbootmybatisg.dao;

import java.util.List;
import org.lwt.springbootmybatisg.entity.Departments;

public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Aug 27 17:38:03 CST 2018
     */
    int insert(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Aug 27 17:38:03 CST 2018
     */
    List<Departments> selectAll();
}